#系统配置
system:
  host: "0.0.0.0"
  port: 5001
#  env: debug
  env: release

mysql:
  host: 127.0.0.1
  port: 3306
  db: go_blog
  user: root
  password: 123456
  log_level: dev

logger:
  level: info
  prefix: '[go-blog]'
  director: logger
  show_line: true   //是否显示行号
  log_in_console: true   //是否显示路径