system:
  host: 0.0.0.0
  port: 5001
  env: release
logger:
  level: info
  prefix: '[go-blog]'
  director: logger
  show_line: false
  log_in_console: false
mysql:
  host: 127.0.0.1
  port: 3306
  db: go_blog
  user: root
  password: "123456"
  log_level: dev
site_info:
  created_at: "2023-02-14"
  bei_an: 豫-109312
  title: 胡晨曦的个人博客
  qq_image: ""
  version: 1.0.0
  email: 2387360024@qq.com
  wechat_image: ""
  name: 晨曦知道
  job: 前端开发
  addr: 河南
  slogan: 晨曦知道
  slogan_en: CHENXIZHIDAO
  web: ""
  bilibili_url: ""
  github_url: ""
email:
  host: smtp.qq.com
  port: 587
  user: 876902310@qq.com
  password: "efuccfdkapljbeeg"
  default_from_email: 晨曦知道
  use_ssl: false
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: 123
qi_niu:
  is_enable: true
  access_key: jPLigjY9K_2TGQ9OJrovjOm618tHk1mLM2AqZWAp
  secret_key: iINKJlO23lBNz41zOLz2t9ntk4KsQ6TOLZoQNHvp
  bucket: chenxizhidao
  cdn: http://sjdwyju8w.hn-bkt.clouddn.com/
  zone: z2
  size: 5
  prefix: "gvb"
qq:
  app_id: xx
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
upload:
  size: 2
  path: uploads/file
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  pool_size: 100